[template]
path = "templates/main_document.toml.j2"

[recovery_template]
path = "templates/recovery_document.toml.j2"

[shard_template]
path = "templates/shard_document.toml.j2"

[signing_key_shard_template]
path = "templates/signing_key_shard_document.toml.j2"

[kit_template]
path = "templates/kit_document.toml.j2"

[qr]
error = "L"
scale = 4
border = 4
kind = "png"
dark = "#0f1f2e"
light = "#ffffffff"
module_shape = "rounded"
payload_encoding = "binary"
